name: Go API Test

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 50

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Install dependencies (latest versions)
        run: |
          go get -u ./...
          go mod tidy

      - name: Run script
        run: go run main.go
