name: Update then Run Scrapers1

on:
  workflow_dispatch:

jobs:

  run_A1:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 18
      matrix:
        scraper: [1,2]

    steps:
      # ✅ Checkout code
      - uses: actions/checkout@v4

      # ✅ Node setup
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # ✅ Install dependencies & Playwright
      - name: Install dependencies
        run: |
          npm install
          npx playwright install chromium

      # ✅ Run scraper & upload DB to Google Drive
      - name: Run scraper & upload DB
        env:
          GDRIVE_CLIENT_ID: ${{ secrets.GDRIVE_CLIENT_ID }}
          GDRIVE_CLIENT_SECRET: ${{ secrets.GDRIVE_CLIENT_SECRET }}
          GDRIVE_REFRESH_TOKEN: ${{ secrets.GDRIVE_REFRESH_TOKEN }}
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
        run: |
          node --max-old-space-size=4096 scrapper${{ matrix.scraper }}.js
          node uploadDbOAuth.js
