name: Update then Run Scrapers

on:
  workflow_dispatch:

jobs:

# =========================
# JOB 1 — UPDATE PREFIXES
# =========================
  run_A1:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 18
      matrix:
        scraper: [1,2]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: updated-scrappers
          path: .
      
      - name: Create service account file
        run: echo '${{ secrets.GDRIVE_KEY }}' > service-account.json
        
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: |
          npm install
          npx playwright install chromium

      - run: node --max-old-space-size=4096 scrapper${{ matrix.scraper }}.js
